# Local configuration overrides for Windows
# This file disables plugins that are problematic on Windows or require extra dependencies.

plugins:
  - jekyll-archives-v2
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  # - jekyll-imagemagick (Disabled locally)
  # - jekyll-jupyter-notebook (Disabled locally)
  - jekyll-link-attributes
  # - jekyll-minifier (Disabled locally)
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs
  # - jekyll-terser (Disabled locally)
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

imagemagick:
  enabled: false

jekyll-minifier:
  enabled: false
